-- =============================================================================
-- OmniDoxa Pipeline - Staging Schema
-- =============================================================================
-- Purpose: Staging tables for new article ingestion, analysis, and promotion
-- Created: 2026-02-28
-- Phase: 1.1 - Database Schema Creation
--
-- This schema supports:
-- - Pipeline run tracking
-- - Category-based article staging
-- - Deduplication (URL, content hash, fuzzy title, cross-category)
-- - Analysis job tracking (Twitter, Reddit, AI sentiment)
-- - Promotion to live tables
--
-- Design Notes:
-- - All tables use INTEGER PRIMARY KEY AUTOINCREMENT for SQLite/Turso
-- - CHECK constraints enforce enum values (no invalid statuses)
-- - Foreign keys with ON DELETE CASCADE (cleanup on run deletion)
-- - Indexes optimized for common queries (run lookups, dedup checks)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Pipeline Run Tracker
-- -----------------------------------------------------------------------------
-- Tracks each pipeline execution (full refresh, category refresh, keyword search)
CREATE TABLE pipeline_runs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  run_type TEXT NOT NULL CHECK(run_type IN ('full_refresh', 'category_refresh', 'keyword_search')),
  trigger_source TEXT NOT NULL CHECK(trigger_source IN ('cron', 'manual', 'conversational')),
  trigger_context TEXT,              -- JSON: { user_request, function_call, params }
  started_at TEXT NOT NULL,
  completed_at TEXT,
  status TEXT DEFAULT 'running' CHECK(status IN ('running', 'analyzing', 'promoting', 'complete', 'failed', 'cancelled')),
  current_stage TEXT,
  error_message TEXT,
  config TEXT NOT NULL               -- JSON: { categories, keywords, target_counts, etc. }
);

-- -----------------------------------------------------------------------------
-- Category Status Tracker
-- -----------------------------------------------------------------------------
-- Tracks article fetching progress per category within a run
-- Supports target counts, pull attempts, and repull logic
CREATE TABLE category_status (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  run_id INTEGER NOT NULL REFERENCES pipeline_runs(id) ON DELETE CASCADE,
  category TEXT NOT NULL,
  target_count INTEGER DEFAULT 5,
  current_count INTEGER DEFAULT 0,
  pull_attempts INTEGER DEFAULT 0,
  status TEXT DEFAULT 'pending' CHECK(status IN ('pending', 'fetching', 'ready', 'complete', 'failed')),
  updated_at TEXT DEFAULT (datetime('now')),
  UNIQUE(run_id, category)
);

-- -----------------------------------------------------------------------------
-- Staging Articles
-- -----------------------------------------------------------------------------
-- Temporary storage for fetched articles before deduplication and promotion
-- Includes normalized fields for dedup matching (URL, title, content hash)
CREATE TABLE staging_articles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  run_id INTEGER NOT NULL REFERENCES pipeline_runs(id) ON DELETE CASCADE,
  category TEXT NOT NULL,
  title TEXT NOT NULL,
  title_normalized TEXT NOT NULL,
  description TEXT,
  url TEXT NOT NULL,
  url_normalized TEXT NOT NULL,
  content_hash TEXT NOT NULL,
  source TEXT,
  image_url TEXT,
  published_at TEXT,
  fetched_at TEXT DEFAULT (datetime('now')),
  pull_batch INTEGER DEFAULT 1,
  status TEXT DEFAULT 'staged' CHECK(status IN ('staged', 'selected', 'rejected')),
  rejection_reason TEXT,
  created_at TEXT DEFAULT (datetime('now'))
);

-- -----------------------------------------------------------------------------
-- Analysis Job Tracker
-- -----------------------------------------------------------------------------
-- Tracks analysis tasks (Twitter, Reddit, AI sentiment) for staged articles
-- Supports retry logic with attempt counting and max attempts
CREATE TABLE analysis_jobs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  run_id INTEGER NOT NULL REFERENCES pipeline_runs(id) ON DELETE CASCADE,
  article_id INTEGER NOT NULL REFERENCES staging_articles(id) ON DELETE CASCADE,
  job_type TEXT NOT NULL CHECK(job_type IN ('twitter', 'reddit', 'ai_sentiment')),
  status TEXT DEFAULT 'pending' CHECK(status IN ('pending', 'running', 'complete', 'failed', 'skipped')),
  attempt_count INTEGER DEFAULT 0,
  max_attempts INTEGER DEFAULT 3,
  started_at TEXT,
  completed_at TEXT,
  error_message TEXT,
  UNIQUE(run_id, article_id, job_type)
);

-- -----------------------------------------------------------------------------
-- Staging Viewpoints
-- -----------------------------------------------------------------------------
-- Staged political viewpoint summaries (left, center, right) for articles
-- Generated by analysis jobs before promotion to live tables
CREATE TABLE staging_viewpoints (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  run_id INTEGER NOT NULL REFERENCES pipeline_runs(id) ON DELETE CASCADE,
  article_id INTEGER NOT NULL REFERENCES staging_articles(id) ON DELETE CASCADE,
  lean TEXT NOT NULL CHECK(lean IN ('left', 'center', 'right')),
  summary TEXT,
  sentiment_score REAL,
  created_at TEXT DEFAULT (datetime('now')),
  UNIQUE(run_id, article_id, lean)
);

-- -----------------------------------------------------------------------------
-- Staging Social Posts
-- -----------------------------------------------------------------------------
-- Staged social media posts (Twitter, Reddit, Threads) linked to viewpoints
-- Includes sentiment analysis and political leaning metadata
CREATE TABLE staging_social_posts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  run_id INTEGER NOT NULL REFERENCES pipeline_runs(id) ON DELETE CASCADE,
  viewpoint_id INTEGER NOT NULL REFERENCES staging_viewpoints(id) ON DELETE CASCADE,
  article_id INTEGER NOT NULL,
  source TEXT NOT NULL CHECK(source IN ('twitter', 'reddit', 'threads')),
  author TEXT,
  content TEXT NOT NULL,
  url TEXT,
  platform_id TEXT,
  likes INTEGER DEFAULT 0,
  retweets INTEGER DEFAULT 0,
  timestamp TEXT,
  is_real INTEGER DEFAULT 1,
  political_leaning_source TEXT,
  political_leaning_verified TEXT,
  sentiment_score REAL,
  sentiment_label TEXT CHECK(sentiment_label IN ('positive', 'negative', 'neutral', 'mixed')),
  created_at TEXT DEFAULT (datetime('now'))
);

-- -----------------------------------------------------------------------------
-- Pipeline Lock
-- -----------------------------------------------------------------------------
-- Prevents concurrent NEW data pipeline runs (singleton pattern)
-- Re-analysis operations bypass this lock (direct live updates)
CREATE TABLE pipeline_lock (
  lock_key TEXT PRIMARY KEY DEFAULT 'singleton',
  run_id INTEGER NOT NULL,
  locked_at TEXT NOT NULL,
  CHECK(lock_key = 'singleton')
);

-- =============================================================================
-- INDEXES
-- =============================================================================
-- Optimized for:
-- - Run lookups (by type, status, recent)
-- - Deduplication checks (URL, hash, title normalization)
-- - Article filtering (by run, category, status)
-- - Analysis job queries (by run, article, job type)
-- - Viewpoint/post lookups (by run, article, viewpoint)
-- =============================================================================

-- Run queries (status checks, recent runs)
CREATE INDEX idx_runs_type_status ON pipeline_runs(run_type, status);
CREATE INDEX idx_runs_recent ON pipeline_runs(started_at DESC) WHERE status IN ('running', 'analyzing');

-- Category status lookups
CREATE INDEX idx_category_status_run ON category_status(run_id, status);

-- Article queries (filtering, dedup)
CREATE INDEX idx_staging_articles_run ON staging_articles(run_id, category, status);
CREATE INDEX idx_staging_articles_url ON staging_articles(url_normalized);
CREATE INDEX idx_staging_articles_hash ON staging_articles(content_hash);
CREATE INDEX idx_staging_articles_title ON staging_articles(title_normalized);

-- Analysis job queries
CREATE INDEX idx_analysis_jobs_lookup ON analysis_jobs(run_id, article_id, job_type, status);

-- Viewpoint queries
CREATE INDEX idx_staging_viewpoints_lookup ON staging_viewpoints(run_id, article_id, lean);

-- Social post queries
CREATE INDEX idx_staging_posts_viewpoint ON staging_social_posts(viewpoint_id);
CREATE INDEX idx_staging_posts_article ON staging_social_posts(article_id);

-- =============================================================================
-- END OF SCHEMA
-- =============================================================================
