import { NextRequest, NextResponse } from 'next/server';
import { generateBriefingHTML } from '@/lib/briefing-template';
import { generateFuturesBoxesHTML, generateStockTableWithOutlook } from '@/lib/briefing-layouts';
import type { 
  BriefingConfig, 
  WeatherData, 
  FutureData, 
  StockData, 
  NewsArticle,
  BriefingSection 
} from '@/types/briefing';

// In-memory cache for stock outlooks (1 hour TTL)
const outlookCache = new Map<string, { outlook: string; timestamp: number }>();
const CACHE_TTL = 60 * 60 * 1000; // 1 hour in milliseconds

/**
 * POST /api/briefing/preview
 * 
 * Generates a preview of the morning briefing based on BriefingConfig
 * Returns HTML matching the perfected email format
 */
export async function POST(req: NextRequest) {
  try {
    const config: BriefingConfig = await req.json();
    const sections: BriefingSection[] = [];

    // 1. WEATHER SECTION
    if (config.weather.enabled && config.weather.location) {
      const weatherData = await fetchWeatherData(config.weather.location);
      sections.push({
        type: 'weather',
        title: `🌤️ Weather — ${config.weather.location}`,
        content: weatherData
      });
    }

    // 2. MARKET FUTURES SECTION
    if (config.market.enabled) {
      const futures = await fetchFuturesData();
      const futuresHTML = generateFuturesBoxesHTML(
        futures,
        "Markets showing mixed momentum as investors digest economic data..."
      );
      sections.push({
        type: 'html',
        title: '📊 Market Futures',
        content: futuresHTML
      });
    }

    // 3. STOCKS SECTION (with AI outlooks)
    if (config.stocks.enabled && config.stocks.watchlist.length > 0) {
      const stocks = await fetchStockDataWithOutlooks(config.stocks.watchlist);
      const stocksHTML = generateStockTableWithOutlook(stocks);
      sections.push({
        type: 'html',
        title: '📈 Your Stock Watchlist',
        content: stocksHTML
      });
    }

    // 4. NEWS TOPICS SECTIONS
    if (config.news.enabled && config.news.topics.length > 0) {
      for (const topic of config.news.topics) {
        const articles = await fetchNewsForTopic(topic.heading);
        if (articles.length > 0) {
          sections.push({
            type: 'news',
            title: topic.heading,
            content: articles
          });
        }
      }
    }

    // 5. SMART BRIEFING SECTION
    if (config.smartBriefing?.enabled && config.smartBriefing.topic) {
      try {
        const briefingContent = await fetchSmartBriefing(config.smartBriefing.topic);
        sections.push({
          type: 'grok',
          title: `🧠 Smart Briefing: ${config.smartBriefing.topic}`,
          content: briefingContent
        });
      } catch (error) {
        console.error('Smart Briefing fetch failed:', error);
        // Continue without smart briefing if it fails
      }
    }

    // Generate final HTML using template library
    const html = generateBriefingHTML({
      recipientName: config.personal.name || 'Friend',
      greeting: `Good Morning${config.personal.name ? `, ${config.personal.name}` : ''}`,
      date: new Date().toLocaleDateString('en-US', {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric'
      }),
      time: new Date().toLocaleTimeString('en-US', {
        hour: 'numeric',
        minute: '2-digit',
        timeZoneName: 'short'
      }),
      headerGradient: 'linear-gradient(135deg, #6b21a8 0%, #a855f7 100%)',
      sections,
      footer: 'Generated by OmniDoxa • Powered by Skippy the Magnificent 🍺'
    });

    return NextResponse.json({
      success: true,
      html,
      generated_at: new Date().toISOString(),
      sections_count: sections.length
    });

  } catch (error) {
    console.error('Preview generation error:', error);
    return NextResponse.json(
      { 
        success: false,
        error: 'Failed to generate preview',
        message: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
}

/**
 * Fetch weather data (mock data for now, can be replaced with real API)
 */
async function fetchWeatherData(location: string): Promise<WeatherData> {
  // TODO: Replace with real weather API (OpenWeather, WeatherAPI, etc.)
  // For preview, using mock data that looks realistic
  
  return {
    temperature: 68,
    weatherDescription: 'Partly Cloudy',
    windSpeed: 8,
    windDirection: 'NE',
    forecast: [
      { dayName: 'Today', high: 72, low: 58, weatherDescription: 'Partly Cloudy' },
      { dayName: 'Tomorrow', high: 75, low: 60, weatherDescription: 'Sunny' },
      { dayName: 'Friday', high: 70, low: 56, weatherDescription: 'Scattered Showers' }
    ]
  };
}

/**
 * Fetch market futures data (mock data for now)
 */
async function fetchFuturesData(): Promise<FutureData[]> {
  // TODO: Replace with real futures API (Yahoo Finance, Alpha Vantage, etc.)
  
  return [
    {
      symbol: 'ES',
      name: 'S&P 500',
      price: 5234.50,
      change: 12.75,
      changePercent: 0.24,
      error: false
    },
    {
      symbol: 'YM',
      name: 'Dow Jones',
      price: 38456.20,
      change: -45.30,
      changePercent: -0.12,
      error: false
    },
    {
      symbol: 'NQ',
      name: 'Nasdaq',
      price: 18234.80,
      change: 85.60,
      changePercent: 0.47,
      error: false
    }
  ];
}

/**
 * Fetch stock data with AI-generated outlooks
 */
async function fetchStockDataWithOutlooks(watchlist: Array<{ symbol: string; name: string }>): Promise<StockData[]> {
  const stocksWithOutlooks: StockData[] = [];

  for (const stock of watchlist) {
    try {
      // Fetch stock price (using mock data for preview)
      const priceData = await fetchStockPrice(stock.symbol);
      
      // Generate AI outlook
      const outlook = await generateStockOutlook(
        stock.symbol,
        priceData.price,
        priceData.changePercent
      );

      stocksWithOutlooks.push({
        symbol: stock.symbol,
        name: stock.name,
        price: priceData.price,
        change: priceData.change,
        changePercent: priceData.changePercent,
        outlook,
        error: false
      });
    } catch (error) {
      console.error(`Failed to fetch data for ${stock.symbol}:`, error);
      stocksWithOutlooks.push({
        symbol: stock.symbol,
        name: stock.name,
        price: 0,
        change: 0,
        changePercent: 0,
        outlook: 'Data unavailable',
        error: true
      });
    }
  }

  return stocksWithOutlooks;
}

/**
 * Fetch stock price data (mock for preview)
 */
async function fetchStockPrice(symbol: string): Promise<{ price: number; change: number; changePercent: number }> {
  // TODO: Replace with real stock API (Yahoo Finance, Alpha Vantage, Polygon.io, etc.)
  
  // Mock data for common symbols
  const mockPrices: Record<string, { price: number; change: number; changePercent: number }> = {
    'AAPL': { price: 182.45, change: 2.35, changePercent: 1.31 },
    'GOOGL': { price: 142.80, change: -0.95, changePercent: -0.66 },
    'MSFT': { price: 415.20, change: 5.60, changePercent: 1.37 },
    'TSLA': { price: 248.90, change: -3.20, changePercent: -1.27 },
    'AMZN': { price: 178.35, change: 1.85, changePercent: 1.05 },
    'NVDA': { price: 875.50, change: 12.40, changePercent: 1.44 },
    'META': { price: 485.30, change: -2.15, changePercent: -0.44 },
  };

  if (mockPrices[symbol]) {
    return mockPrices[symbol];
  }

  // Default mock data for unknown symbols
  return {
    price: 100 + Math.random() * 100,
    change: (Math.random() - 0.5) * 10,
    changePercent: (Math.random() - 0.5) * 5
  };
}

/**
 * Generate AI stock outlook using free LLM model
 * Caches results for 1 hour to reduce API calls
 */
async function generateStockOutlook(
  symbol: string, 
  price: number, 
  changePercent: number
): Promise<string> {
  // Check cache first
  const cached = outlookCache.get(symbol);
  if (cached && Date.now() - cached.timestamp < CACHE_TTL) {
    return cached.outlook;
  }

  try {
    const response = await fetch('https://openrouter.ai/api/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${process.env.OPENROUTER_API_KEY}`,
        'Content-Type': 'application/json',
        'HTTP-Referer': process.env.NEXT_PUBLIC_SITE_URL || 'https://omnidoxa.vercel.app',
        'X-Title': 'OmniDoxa Stock Outlook'
      },
      body: JSON.stringify({
        model: 'meta-llama/llama-3.2-3b-instruct:free',
        messages: [{
          role: 'user',
          content: `Generate a brief 1-sentence stock market outlook for ${symbol} (current price $${price.toFixed(2)}, ${changePercent > 0 ? '+' : ''}${changePercent.toFixed(2)}% change). Keep it under 150 characters, professional, and market-focused. No fluff.`
        }],
        max_tokens: 100,
        temperature: 0.7
      })
    });

    if (!response.ok) {
      throw new Error(`OpenRouter API error: ${response.status}`);
    }

    const data = await response.json();
    const outlook = data.choices?.[0]?.message?.content?.trim();

    if (!outlook) {
      throw new Error('No outlook generated');
    }

    // Truncate to 150 chars if needed
    const truncated = outlook.length > 150 
      ? outlook.substring(0, 147) + '...' 
      : outlook;

    // Cache the result
    outlookCache.set(symbol, {
      outlook: truncated,
      timestamp: Date.now()
    });

    return truncated;

  } catch (error) {
    console.error(`AI outlook generation failed for ${symbol}:`, error);
    // Fallback to generic outlook based on price movement
    return generateGenericOutlook(changePercent);
  }
}

/**
 * Generate generic outlook based on price movement (fallback)
 */
function generateGenericOutlook(changePercent: number): string {
  if (changePercent > 3) return "Strong upward momentum with significant gains this week";
  if (changePercent > 1) return "Positive trend showing steady growth";
  if (changePercent > 0) return "Stable performance with modest gains";
  if (changePercent > -1) return "Minor pullback, tracking broader market trends";
  if (changePercent > -3) return "Experiencing downward pressure, monitor for support";
  return "Significant weakness, potential opportunity for value investors";
}

/**
 * Fetch news articles for a topic (mock data for preview)
 */
async function fetchNewsForTopic(topic: string): Promise<NewsArticle[]> {
  // TODO: Replace with real news API or OmniDoxa database query
  
  // Mock articles for preview
  return [
    {
      title: `${topic}: Major developments in the sector`,
      description: 'Industry experts weigh in on recent changes and what they mean for the future...',
      url: 'https://example.com/article1',
      source: 'Financial Times'
    },
    {
      title: `Breaking: ${topic} sees unexpected growth`,
      description: 'New data reveals surprising trends that analysts didn\'t predict...',
      url: 'https://example.com/article2',
      source: 'Bloomberg'
    },
    {
      title: `Analysis: The future of ${topic}`,
      description: 'Long-term projections suggest significant changes ahead for the industry...',
      url: 'https://example.com/article3',
      source: 'Reuters'
    }
  ];
}

/**
 * Fetch Smart Briefing content from /api/smart-briefing
 */
async function fetchSmartBriefing(topic: string): Promise<string> {
  try {
    const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000';
    const response = await fetch(`${baseUrl}/api/smart-briefing`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ topic })
    });

    if (!response.ok) {
      throw new Error(`Smart Briefing API error: ${response.status}`);
    }

    const data = await response.json();
    return data.analysis || data.briefing || '<p>Smart Briefing content unavailable</p>';
    
  } catch (error) {
    console.error('Smart Briefing fetch error:', error);
    // Return fallback content
    return `
      <h3>Smart Briefing: ${topic}</h3>
      <p><em>Smart Briefing is currently unavailable. Please try again later.</em></p>
    `;
  }
}
